#pragma once

#include <Arduino.h>

#include "Config.h"

const byte RUNTIME_CONFIG_MAX_RGA_MASSES = 16;

struct RuntimeConfig {
  RuntimeConfig()
  {
    RGA_NUM_MASSES = ::RGA_NUM_MASSES < RUNTIME_CONFIG_MAX_RGA_MASSES
      ? ::RGA_NUM_MASSES
      : RUNTIME_CONFIG_MAX_RGA_MASSES;
    for (byte i = 0; i < RGA_NUM_MASSES && i < RUNTIME_CONFIG_MAX_RGA_MASSES; i++) {
      RGA_MASSES[i] = ::RGA_MASSES[i];
    }
  }

  bool AUTOSTART_ON_BOOT = ::AUTOSTART_ON_BOOT;
  bool PUMP_ON_AT_STARTUP = ::PUMP_ON_AT_STARTUP;
  byte RGA_MASSES[RUNTIME_CONFIG_MAX_RGA_MASSES] = {};
  byte RGA_NUM_MASSES = 0;
  unsigned long RGA_READY_BEFORE_ACQUISITION_MS = ::RGA_READY_BEFORE_ACQUISITION_MS;
  unsigned long TURBO_READY_BEFORE_RGA_MS = ::TURBO_READY_BEFORE_RGA_MS;
  unsigned long CHAMBER_VALVE_TOGGLE_INTERVAL_MS = ::CHAMBER_VALVE_TOGGLE_INTERVAL_MS;
  unsigned long MIN_EXPERIMENT_INTERVAL_MS = ::MIN_EXPERIMENT_INTERVAL_MS;
  unsigned long MAX_EXPERIMENT_INTERVAL_MS = ::MAX_EXPERIMENT_INTERVAL_MS;
  float OXYGEN_MIN_MG_L = ::OXYGEN_MIN_MG_L;
  float OXYGEN_MAX_MG_L = ::OXYGEN_MAX_MG_L;
};
